name: Build

on:
  push:
    branches: [ master, 3.x ]
  pull_request:
    branches: [ master, 3.x ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [8, 11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Production Build with Maven
        run: mvn clean package -Pproduction
      - name: Directory Build with Maven
        run: mvn clean install -Pdirectory