name: Build

on:
  push:
    branches: [ 2.x ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [8, 11]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Production Build with Maven
        run: mvn clean package -Pproduction
      - name: Directory Build with Maven
        run: mvn clean install -Pdirectory
        
  notify:
    name: 'Submodule Notify Parent'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
      - name: 'Submodule Notify Parent'
        env: 
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          PARENT_REPO: F0rce/vaadin-add-ons
          PARENT_BRANCH: main
          WORKFLOW_ID: 32255266
        run: |
          curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
